<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <GenerateSerializationAssemblies>Off</GenerateSerializationAssemblies>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>C:\Users\Mordrog\AppData\Roaming\Thunderstore Mod Manager\DataFolder\RiskOfRain2\profiles\Mordrog\BepInEx\plugins\Mordrog-ForceItemsEqualShare\</OutputPath>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
		<PackageReference Include="BepInEx.Analyzers" Version="1.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>

		<PackageReference Include="BepInEx.Core" Version="5.4.21" />
		<PackageReference Include="R2API.Prefab" Version="1.0.*" />
		<PackageReference Include="UnityEngine.Modules" Version="2021.3.33" IncludeAssets="compile" />
		<PackageReference Include="RiskOfRain2.GameLibs" Version="1.4.0.0-r.0" />
		<PackageReference Include="MMHOOK.RoR2" Version="2025.11.19" NoWarn="NU1701" />
  </ItemGroup>

</Project>
